modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/PixilareGames/PixelCore/issues"

[[mods]] #mandatory
	modId="pixelcore"
	version="1.0"
	displayName="Pixel Core"
	updateJSONURL="https://github.com/PixilareGames/PixelCore/tree/master/1.14/Normal%201.14.4"
	displayURL="https://github.com/PixilareGames/PixelCore"
	logoFile="pixelcore.png"
	credits="Herobrain_gamer For Coding"
	authors="Herobrain_gamer"
	description='''Ian Please Add More Information'''

[[dependencies.pixelcore]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.pixelcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"