modLoader="javafml"
loaderVersion="[26,)"

[[mods]] #mandatory
	modId="pixelcore"
	version="1.0"
	displayName="Pixel Core"
	credits="Herobrain_gamer For Coding, GamerGabriel For Textures, TheTrueDuility For Helping"
	authors="Herobrain_gamer, GamerGabriel, TheTrueDuility"
	description='''Ian Please Add More Information'''

[[dependencies.pixelcore]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.pixelcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"